In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
a = torch.ones(3)

In [3]:
a[1]

tensor(1.)

In [4]:
b = torch.tensor([[1,2],[2,3],[3,4]])

In [5]:
b.shape

torch.Size([3, 2])

In [6]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2126,0.1789,0.3451])

In [8]:
batch_t = torch.randn(2,5,5,6)

In [9]:
torch.linspace(2,10, steps = 25)

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])

In [10]:
torch.logspace(2,10, steps = 25)

tensor([1.0000e+02, 2.1544e+02, 4.6416e+02, 1.0000e+03, 2.1544e+03, 4.6416e+03,
        1.0000e+04, 2.1544e+04, 4.6416e+04, 1.0000e+05, 2.1544e+05, 4.6416e+05,
        1.0000e+06, 2.1544e+06, 4.6416e+06, 1.0000e+07, 2.1544e+07, 4.6416e+07,
        1.0000e+08, 2.1544e+08, 4.6416e+08, 1.0000e+09, 2.1544e+09, 4.6416e+09,
        1.0000e+10])

### Probability distributions

In [12]:
torch.manual_seed(1234)
torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In [14]:
torch.Tensor(4,4).uniform_(0,1)

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

In [16]:
torch.bernoulli(torch.Tensor(4,4).uniform_(0,1))

tensor([[0., 0., 0., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 0., 0., 0.]])

In [17]:
torch.Tensor([10,12,15,34,36,39,40,47,50,67,72,89])

tensor([10., 12., 15., 34., 36., 39., 40., 47., 50., 67., 72., 89.])

In [22]:
torch.multinomial(torch.tensor([10.,12.,15.,34.,36.,39.,40.,47.,50.,67.,72.,89.]),3, replacement=True)

tensor([8, 5, 8])

In [28]:
torch.normal(mean = torch.arange(1.,11.),
            std = torch.arange(1.,0,-0.1))

tensor([ 3.3648,  3.0405,  4.2034,  3.1825,  5.0349,  6.3201,  6.1739,  7.7440,
         9.1312, 10.0826])

In [27]:
torch.normal(mean = 0.5,
            std = torch.arange(1.,6.))

tensor([  0.7589,  -0.4499,   0.1011, -11.1886,  -6.3243])

In [29]:
torch.normal(mean = 0.5,
            std = torch.arange(0.2,0.6))

tensor([0.6731])

In [30]:
from torch.autograd import Variable

In [31]:
Variable(torch.ones(2,2), requires_grad=True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [32]:
a, b = 12,23
x1 = Variable(torch.randn(a,b), requires_grad=True)
x2 = Variable(torch.randn(a,b), requires_grad=True)
x3 = Variable(torch.randn(a,b), requires_grad=True)

In [33]:
c = x1 * x2
d = a + x3
e = torch.sum(d)

e.backward()

print(e)

tensor(3334.3762, grad_fn=<SumBackward0>)


In [36]:
torch.mean(torch.randn(4,5),dim = 1)

tensor([-0.4018, -0.7195,  0.4343, -0.8953])

In [62]:
# gradient computation

def forward_prop(x):
    return x * w

x_data = [11.0,22.0,33.0]
y_data = [21.0,14.0,64.0]

w = Variable(torch.Tensor([1.0]), requires_grad = True)

print("Predict (before training) ", 4, forward_prop(4).data[0])

Predict (before training)  4 tensor(4.)


In [63]:
def loss(x, y):
    y_pred = forward_prop(x)
    return (y_pred - y) * (y_pred - y)

In [64]:
for epoch in range(10):
    for x_val, y_val in zip(x_data,y_data):
        l = loss(x_val,y_val)
        l.backward()
        w.data = w.data - 0.01 * w.grad.data
        
        w.grad.data.zero_()
        
    print("progess: ", epoch, l.data[0])

progess:  0 tensor(604238.8125)
progess:  1 tensor(3.9481e+10)
progess:  2 tensor(2.5900e+15)
progess:  3 tensor(1.6991e+20)
progess:  4 tensor(1.1146e+25)
progess:  5 tensor(7.3118e+29)
progess:  6 tensor(4.7966e+34)
progess:  7 tensor(inf)
progess:  8 tensor(inf)
progess:  9 tensor(inf)


In [65]:
print("Predict (fater training) ", 4, forward_prop(4).data[0])

Predict (fater training)  4 tensor(-9.2687e+24)


In [72]:
from torch import FloatTensor

a = Variable(FloatTensor([5]))
print(a)
weights = [Variable(FloatTensor([i]), requires_grad = True) for i in (12, 53, 91, 73)]
print(weights)
w1,w2,w3,w4 = weights

b = w1 * a
print(b)
c = w2 * a
print(c)
d = w3 * b + w4 * c
print(d)
Loss = (10 - d)

Loss.backward()

for index , weight in enumerate(weights, start =1):
    gradients , *_ = weight.grad.data
    print(f"Gradients of w{index} w.r.t Loss : {gradients}")

tensor([5.])
[tensor([12.], requires_grad=True), tensor([53.], requires_grad=True), tensor([91.], requires_grad=True), tensor([73.], requires_grad=True)]
tensor([60.], grad_fn=<MulBackward0>)
tensor([265.], grad_fn=<MulBackward0>)
tensor([24805.], grad_fn=<AddBackward0>)
Gradients of w1 w.r.t Loss : -455.0
Gradients of w2 w.r.t Loss : -365.0
Gradients of w3 w.r.t Loss : -60.0
Gradients of w4 w.r.t Loss : -265.0
